#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME=domain
PROG=/usr/lib/ddns/update.sh
CONFIG=/etc/config/domain

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file "$CONFIG"
    procd_close_instance
    
    # 启动所有启用的DDNS配置
    uci -q get domain.@domain[0] >/dev/null 2>&1 && {
        uci -q show domain | grep -E 'domain\.(@domain\[[0-9]+\])?\.enabled=1' | \
        while read line; do
            config_id=$(echo "$line" | cut -d'=' -f1 | cut -d'.' -f2)
            [ -n "$config_id" ] && {
                echo "Starting DDNS for $config_id"
                $PROG "$config_id" &
            }
        done
    }
}

stop_service() {
    killall -9 update.sh 2>/dev/null
}

reload_service() {
    stop
    start
}

boot() {
    start
}